### ISSUE TITLE
Indentation issue

### ISSUE THREAD

**Issue by kylebeggs** [kylebeggs/POD-RBF#6]
```python
Traceback (most recent call last):
  File "/euler/pro/code/POD-RBF/examples/heat-conduction/2d-heat.py", line 48, in <module>
    import pod_rbf as p
  File "/home/kylebeggs/.local/lib/python3.10/site-packages/pod_rbf/__init__.py", line 1, in <module>
    from .pod_rbf import *
  File "/home/kylebeggs/.local/lib/python3.10/site-packages/pod_rbf/pod_rbf.py", line 155
    def _buildRBFInferenceMatrix(self, inf_params):
                                                   ^
IndentationError: unindent does not match any outer indentation level
```

**Comment by yamanatoo** [comment]
https://github.com/kylebeggs/POD-RBF/pull/7#issue-1885328706

**Comment by kylebeggs** [comment]
Closed via #7

**Comment by kylebeggs** [comment]
@yamanatoo it works for you? I am still having issues

**Comment by yamanatoo** [comment]
Sorry again. This one is tested with the 2d-heat example
https://github.com/kylebeggs/POD-RBF/pull/8#issue-1892166473

**Comment by kylebeggs** [comment]
Thank you @yamanatoo, I tested also and uploaded to PyPi so you can update there.
